config/routes.rb
TheFoveonBbs::Application.routes.draw do
  namespace :admin do
    resources :messages, only: [:index] do
      collection do
        delete :bulk_destroy
      end
    end
    resources :comments, only: [:index] do
      collection do
        delete :bulk_destroy
      end
    end
  end

  resources :messages do
    collection do
      get 'trees'
      get 'feed'
    end
    member do
      get 'thread'
      get 'delete_confirm'
    end
    resources :comments do
      member do
        get 'delete_confirm'
        get 'reply'
      end
    end
  end
  resources :photos

  root to: 'messages#trees'
end

app/models/message.rb
class Message < ActiveRecord::Base
  include Entry
  extend EntryExtend

  has_many :comments, ->{order(:created_at)}, dependent: :destroy

  scope :newer, ->(created_at) { where('created_at >= ?', created_at) }

  def self.search_from_input(input)
    comment_where = Comment.where_from_input(input)
    comment_select =  Comment.select(:message_id).where(comment_where)

    message_where = Message.where_from_input(input)

    Message.where(Message.where(message_where).where(id: comment_select).where_values.reduce(:or))
  end

  def current_page
    count = Message.newer(self.created_at).count
    (count.to_f / Kaminari.config.default_per_page).ceil
  end
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < Admin::ApplicationController
  def index
    @messages = Message.desc.page(params[:page]).per(Settings.admin.messages.per_page)
  end

  def bulk_destroy
    ActiveRecord::Base.transaction do
      Message.where(id: params[:messages]).destroy_all
    end

    redirect_to admin_messages_path(page: params[:page])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :find_message, only: [:show, :edit, :update, :thread, :delete_confirm, :destroy]
  after_action :save_cookies, only: [:create, :update]

  def new
    @message = Message.new(load_cookies)
    @message.build_photos_up_to_max
  end

  def create
    message_params = params.require(:message).permit(Message.permitted_create_params)
    @message = Message.new(message_params)

    if @message.save
      @message.log_request(request)
      redirect_to thread_message_path(@message)
    else
      @message.build_photos_up_to_max
      render action: :new
    end
  end

  def show
  end


  def edit
    @message.build_photos_up_to_max
  end

  def update
    message_params = params.require(:message).permit(Message.permitted_update_params)

    if @message.update_attributes(message_params)
      @message.log_request(request)
      redirect_to thread_message_path(@message)
    else
      @message.build_photos_up_to_max
      render action: :edit
    end
  end

  # get
  def delete_confirm
  end

  def destroy
    message_params = params.require(:message).permit(Message.permitted_destroy_params)
    @message.assign_attributes(message_params)

    if @message.valid?
      if @message.comments.empty?
        @message.destroy
      else
        @message.update_attributes(content: 'Deleted.')
        @message.log_request(request)
        @message.photos.destroy_all
      end
      redirect_to action: :trees
    else
      render action: :delete_confirm
    end
  end

  # get
  def trees
    if params[:words].present?
      @messages = Message.search_from_input(params[:words]).desc.page(params[:page])
    else
      @messages = Message.desc.page(params[:page])
    end
  end

  # get
  def feed
    messages = Message.desc.limit(10)
    comments = Comment.desc.limit(10)
    entries = messages.concat(comments).sort do |a, b|
      a.created_at <=> b.created_at
    end
    @entries = entries.reverse.slice(0, 10)

    render :layout => false
  end

  # get
  def thread
  end

  private

  def find_message
    @message = Message.find(params[:id])
  end

  def load_cookies
    data = Hash.new
    Message.cookie_keys.map do |key|
      data[key] = cookies.signed[key]
    end

    data
  end

  def save_cookies
    return unless response.status == Rack::Utils.status_code(:found)
    
    Message.cookie_keys.each do |key|
      cookies.signed[key] = {value: @message[key], path: root_path, expires: 1.year.from_now}
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def url_for_entry(entry)
    case entry
    when Message
      message_url(entry)
    when Comment
      message_comment_url(entry.message, entry)
    end
  end
end

app/views/messages/_branch_headline.html.haml
.row-fluid.branch.tree_text
  .span8= link_to(entry.title, thread_message_path(entry, anchor: entry))
  .span4
    = entry.author
    - if entry.homepage.present?
      = link_to('', entry.url, class: 'icon-home', target: '_blank')
    - if entry.mail.present?
      = mail_to(entry.mail, '', class: 'icon-envelope')

app/views/messages/_comment_headline.html.haml
.row-fluid.comment_base
  .span8.entry_headline= link_to(entry.title, thread_message_path(entry.message, anchor: entry))
  .span2.entry_headline
    = entry.author
    - if entry.homepage.present?
      = link_to('', entry.url, class: 'icon-home', target: '_blank')
    - if entry.mail.present?
      = mail_to(entry.mail, '', class: 'icon-envelope')
  .span2.entry_headline= I18n.localize(entry.created_at, :format => :short)

app/views/messages/_form.html.haml
= render partial: 'entry_form', object: form, as: :form, locals: {entry: message}

app/views/messages/_message_headline.html.haml
.row-fluid
  .span8.entry_headline
    = link_to(entry.title, thread_message_path(entry))

  .span2.entry_headline
    = entry.author
    - if entry.homepage.present?
      = link_to('', entry.url, class: 'icon-home', target: '_blank')
    - if entry.mail.present?
      = mail_to(entry.mail, '', class: 'icon-envelope')
  .span2.entry_headline= I18n.localize(entry.created_at, :format => :short)

app/views/messages/_root_headline.html.haml
.row-fluid.tree_text
  .span8= link_to(entry.title, thread_message_path(entry))
  .span4
    = entry.author
    - if entry.homepage.present?
      = link_to('', entry.url, class: 'icon-home', target: '_blank')
    - if entry.mail.present?
      = mail_to(entry.mail, '', class: 'icon-envelope')

app/views/messages/_thread.html.haml
.row-fluid.thread
  .row-fluid.thread_header
    .row-fluid
      .span7.entry_headline
        = entry.title
        %a(name="#{entry.id}")
        - if entry.photos.present?
          = link_to('', message_path(entry), class: 'icon-camera')
        - if entry.new_entry?
          %i.icon-gift.new-entry
        .button_group
          - if button_display
            = link_to('', new_message_comment_path(entry), method: 'get', class: 'icon-share-alt')
            = link_to('', edit_message_path(entry), method: 'get', class: 'icon-edit')
            = link_to('', delete_confirm_message_path(entry), method: 'get', class: 'icon-trash')
      .span5.entry_headline
        = entry.author
        - if entry.homepage.present?
          = link_to('', entry.homepage, class: 'icon-home', target: '_blank')
        - if entry.mail.present?
          = mail_to(entry.mail, '', class: 'icon-envelope')
        .entry_headline_date
          = I18n.localize(entry.created_at, :format => :short)
  .row-fluid
    .span12.thread_body
      = raw Rinku.auto_link(simple_format(entry.content), mode=:all, 'target="_blank"')
  - if thumbnail_display && entry.photos.present?
    .row-fluid.thread_photo_group
      - entry.photos.each do |photo|
        = link_to(image_tag(photo.photo_data.thumb.to_s, class: 'img-polaroid thread_photo', alt: photo.title), photo_path(photo), title: photo.title)

app/views/messages/_thread_buttons.html.haml
.row-fluid
  .page_header
    .pagination.pagination_base
      %ul
        %li= link_to('', root_path, class: 'icon-home')
        %li= link_to('', trees_messages_path(page: current_page), class: 'icon-th-list')

app/views/messages/_thread_smart_phone.html.haml
.row-fluid.thread
  .row-fluid.thread_header
    .row-fluid
      .entry_headline
        = entry.title
        - if entry.photos.present?
          = link_to('', message_path(entry), class: 'icon-camera')
        - if entry.new_entry?
          %i.icon-gift.new-entry
    .row-fluid
      .entry_headline
        = entry.author
        - if entry.homepage.present?
          = link_to('', entry.homepage, class: 'icon-home', target: '_blank')
        - if entry.mail.present?
          = mail_to(entry.mail, '', class: 'icon-envelope')
        .entry_headline_date
          - if button_display
            %span.button_group
              = link_to('', new_message_comment_path(entry), method: 'get', class: 'icon-share-alt')
              = link_to('', edit_message_path(entry), method: 'get', class: 'icon-edit')
              = link_to('', delete_confirm_message_path(entry), method: 'get', class: 'icon-trash')
          = I18n.localize(entry.created_at, :format => :short)
  .row-fluid
    .span12.thread_body
      = raw Rinku.auto_link(simple_format(entry.content), mode=:all, 'target="_blank"')
  - if thumbnail_display && entry.photos.present?
    .row-fluid.thread_photo_group
      - entry.photos.each do |photo|
        = link_to(image_tag(photo.photo_data.thumb.to_s, class: 'img-polaroid thread_photo', alt: photo.title), photo_path(photo), title: photo.title)

app/views/messages/delete_confirm.html.haml
.container-fluid
  .row-fluid
    .page_header
      .pagination.pagination_base
        %ul
          %li= link_to('', root_path, class: 'icon-home')
          %li= link_to('', thread_message_path(@message), class: 'icon-comment')
  = render partial: 'thread', object: @message, as: :entry, locals: {button_display: false, thumbnail_display: true}
  .row_fluid.delete_form
    = form_for(@message, method: :delete, html: { class: 'form-inline' }) do |f|
      = render partial: 'delete_form', object: f, as: :form

app/views/messages/edit.html.haml
= javascript_include_tag "entry_form"
.container-fluid
  .row-fluid
    .page_header
      .pagination.pagination_base
        %ul
          %li= link_to('', root_path, class: 'icon-home')
          %li= link_to('', thread_message_path(@message), class: 'icon-comment')
  .row-fluid
    .entry_form
      = form_for(@message, multipart: true, html: { id:'entry_form', class: 'form-horizontal' }) do |f|
        = render partial: 'form', object:f, as: :form, locals: {message: @message}
        .control-group
          .controls
            = f.submit t('buttons.update'), disable_with: t('buttons.update'), class: 'btn btn-primary'

app/views/messages/new.html.haml
= javascript_include_tag "entry_form"
.container-fluid
  .row-fluid
    .page_header
      .pagination.pagination_base
        %ul
          %li= link_to('', root_path, class: 'icon-home')
  .row-fluid
    .entry_form
      = form_for(@message, multipart: true, html: { id:'entry_form', class: 'form-horizontal' }) do |f|
        = render partial: 'form', object:f, as: :form, locals: {message: @message}
        .control-group
          .controls
            = f.submit t('buttons.create'), disable_with: t('buttons.create'), class: 'btn btn-primary'

app/views/messages/thread.html.haml
.container-fluid
  = render(partial: 'thread_buttons', locals: {current_page: @message.current_page})
  = render(partial: 'messages/thread', object: @message, as: :entry, locals: {button_display: true, thumbnail_display: true})
  = render(partial: 'comments/thread', collection: @message.comments, as: :entry, locals: {button_display: true, thumbnail_display: true})
  = render(partial: 'thread_buttons', locals: {current_page: @message.current_page})

app/views/messages/trees.html.haml
.container-fluid
  = render(partial: 'pager', object: @messages, as: :messages, locals:{params: params})

  - @messages.each do |message|
    .row-fluid.tree
      - style = message.comments.present? ? 'message_headline_base_with_any_branch' : 'message_headline_base_with_no_branch'
      .row-fluid(class=style)
        = render(partial: 'headline',  object: message, as: :entry, locals:{params: params})
      .row-fluid
        = render(partial: 'comments/headline', collection: message.comments, as: :entry, locals:{params: params})

  = render(partial: 'pager', object: @messages, as: :messages, locals:{params: params})

app/views/messages/trees_smart_phone.html.haml
.container-fluid
  = render(partial: 'pager', object: @messages, as: :messages, locals:{params: params})

  - @messages.each do |message|
    .row-fluid.tree
      - style = message.comments.present? ? 'message_headline_base_with_any_branch' : 'message_headline_base_with_no_branch'
      .row-fluid(class=style)
        = render(partial: 'headline',  object: message, as: :entry, locals:{params: params})
      .row-fluid
        = render(partial: 'comments/headline', collection: message.comments, as: :entry, locals:{params: params})