config/routes.rb
TheFoveonBbs::Application.routes.draw do
  namespace :admin do
    resources :messages, only: [:index] do
      collection do
        delete :bulk_destroy
      end
    end
    resources :comments, only: [:index] do
      collection do
        delete :bulk_destroy
      end
    end
  end

  resources :messages do
    collection do
      get 'trees'
      get 'feed'
    end
    member do
      get 'thread'
      get 'delete_confirm'
    end
    resources :comments do
      member do
        get 'delete_confirm'
        get 'reply'
      end
    end
  end
  resources :photos

  root to: 'messages#trees'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Entry
  extend EntryExtend

  belongs_to :message

  validates :message_id, presence: true

  def reply_to(entry)
    raise ArgumentError, "#{entry} does not include Entry" unless entry.kind_of?(Entry)

    self.title = entry.title.gsub(/^/, "Re: ")
    self.content = I18n.t('entry.wrote', author: entry.author) + "\n"
    self.content += entry.content.gsub(/^/, "> ")
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  def index
    @comments = Comment.desc.page(params[:page]).per(Settings.admin.messages.per_page)
  end

  def bulk_destroy
    ActiveRecord::Base.transaction do
      Comment.where(id: params[:comments]).destroy_all
    end

    redirect_to admin_comments_path(page: params[:page])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_message
  before_action :find_comment, only: [:show, :edit, :update, :delete_confirm, :destroy]
  after_action :save_cookies, only: [:create, :update]

  def new
    @comment = Comment.new(load_cookies)
    @comment.build_photos_up_to_max
    @comment.reply_to(@message)
  end

  def reply
    target = @message.comments.find(params[:id])
    @comment = Comment.new(load_cookies)
    @comment.build_photos_up_to_max
    @comment.reply_to(target)

    render action: :new
  end

  def create
    comment_params = params.require(:comment).permit(Comment.permitted_create_params)
    @comment = @message.comments.build(comment_params)

    if @comment.save
      @comment.log_request(request)
      redirect_to thread_message_path(@message, anchor: @comment.id)
    else
      @comment.build_photos_up_to_max
      render action: :new
    end
  end

  def show
  end

  def edit
    @comment.build_photos_up_to_max
  end

  def update
    comment_params = params.require(:comment).permit(Comment.permitted_update_params)

    if @comment.update_attributes(comment_params)
      @comment.log_request(request)
      redirect_to thread_message_path(@message, anchor: @comment.id)
    else
      @comment.build_photos_up_to_max
      render action: :edit
    end

  end

  def delete_confirm
  end

  def destroy
    comment_params = params.require(:comment).permit(Comment.permitted_destroy_params)
    @comment.assign_attributes(comment_params)

    if @comment.valid?
      @comment.destroy
      redirect_to thread_message_path(@message)
    else
      render action: :delete_confirm
    end
  end

  private

  def find_message
    @message =  Message.find(params[:message_id])
  end

  def find_comment
    @comment =  @message.comments.find(params[:id])
  end

  def load_cookies
    data = Hash.new
    Comment.cookie_keys.map do |key|
      data[key] = cookies.signed[key]
    end

    data
  end

  def save_cookies
    return unless response.status == Rack::Utils.status_code(:found)

    Comment.cookie_keys.each do |key|
      cookies.signed[key] = {value: @comment[key], path: root_path, expires: 1.year.from_now}
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= render partial: 'entry_form', object: form, as: :form, locals: {entry: comment}

app/views/comments/_headline.html.haml
.row-fluid.comment_base
  .span7.entry_headline
    = link_to(entry.title, thread_message_path(entry.message, anchor: entry))
    - if entry.photos.present?
      = link_to('', message_comment_path(entry.message, entry), class: 'icon-camera')
    - if entry.new_entry?
      %i.icon-gift.new-entry
    - if params[:words].present? && entry.search_hit?(params[:words])
      %i.icon-star.search-hit
  .span5.entry_headline
    = entry.author
    - if entry.homepage.present?
      = link_to('', entry.homepage, class: 'icon-home', target: '_blank')
    - if entry.mail.present?
      = mail_to(entry.mail, '', class: 'icon-envelope')
    .entry_headline_date
      = I18n.localize(entry.created_at, :format => :short)

app/views/comments/_thread.html.haml
%a(name="#{entry.id}")
.row-fluid.thread
  .row-fluid.thread_header
    .row-fluid
      .span7.entry_headline
        = entry.title
        - if entry.photos.present?
          = link_to('', message_comment_path(entry.message, entry), class: 'icon-camera')
        - if entry.new_entry?
          %i.icon-gift.new-entry
        .button_group
          - if button_display
            = link_to('', reply_message_comment_path(entry.message, entry), method: 'get', class: 'icon-share-alt')
            = link_to('', edit_message_comment_path(entry.message, entry), method: 'get', class: 'icon-edit')
            = link_to('', delete_confirm_message_comment_path(entry.message, entry), method: 'get', class: 'icon-trash')
      .span5.entry_headline
        = entry.author
        - if entry.homepage.present?
          = link_to('', entry.homepage, class: 'icon-home', target: '_blank')
        - if entry.mail.present?
          = mail_to(entry.mail, '', class: 'icon-envelope')
        .entry_headline_date
          = I18n.localize(entry.created_at, :format => :short)
  .row-fluid
    .span12.thread_body
      = raw Rinku.auto_link(simple_format(entry.content), mode=:all, 'target="_blank"')
  - if thumbnail_display && entry.photos.present?
    .row-fluid.thread_photo_group
      - entry.photos.each do |photo|
        = link_to(image_tag(photo.photo_data.thumb.to_s, class: 'img-polaroid thread_photo', alt: photo.title), photo_path(photo), title: photo.title)

app/views/comments/_thread_smart_phone.html.haml
%a(name="#{entry.id}")
.row-fluid.thread
  .row-fluid.thread_header
    .row-fluid
      .entry_headline
        = entry.title
        - if entry.photos.present?
          = link_to('', message_comment_path(entry.message, entry), class: 'icon-camera')
        - if entry.new_entry?
          %i.icon-gift.new-entry
    .row-fluid
      .entry_headline
        = entry.author
        - if entry.homepage.present?
          = link_to('', entry.homepage, class: 'icon-home', target: '_blank')
        - if entry.mail.present?
          = mail_to(entry.mail, '', class: 'icon-envelope')
        .entry_headline_date
          - if button_display
            %span.button_group
              = link_to('', reply_message_comment_path(entry.message, entry), method: 'get', class: 'icon-share-alt')
              = link_to('', edit_message_comment_path(entry.message, entry), method: 'get', class: 'icon-edit')
              = link_to('', delete_confirm_message_comment_path(entry.message, entry), method: 'get', class: 'icon-trash')
          = I18n.localize(entry.created_at, :format => :short)
  .row-fluid
    .span12.thread_body
      = raw Rinku.auto_link(simple_format(entry.content), mode=:all, 'target="_blank"')
  - if thumbnail_display && entry.photos.present?
    .row-fluid.thread_photo_group
      - entry.photos.each do |photo|
        = link_to(image_tag(photo.photo_data.thumb.to_s, class: 'img-polaroid thread_photo', alt: photo.title), photo_path(photo), title: photo.title)

app/views/comments/delete_confirm.html.haml
.container-fluid
  .row-fluid
    .page_header
      .pagination.pagination_base
        %ul
          %li= link_to('', root_path, class: 'icon-home')
          %li= link_to('', thread_message_path(@message, anchor: @comment.id), class: 'icon-comment')
  = render partial: 'thread', object: @comment, as: :entry, locals: {button_display: false, thumbnail_display: true}
  .row_fluid.delete_form
    = form_for([@message, @comment], method: :delete, html: { class: 'form-inline' }) do |f|
      = render partial: 'delete_form', object: f, as: :form

app/views/comments/edit.html.haml
= javascript_include_tag "entry_form"
.container-fluid
  .row-fluid
    .page_header
      .pagination.pagination_base
        %ul
          %li= link_to('', root_path, class: 'icon-home')
          %li= link_to('', thread_message_path(@message, anchor: @comment.id), class: 'icon-comment')
  .row-fluid
    .entry_form
      = form_for([@message, @comment], multipart: true, html: { id:'entry_form', class: 'form-horizontal' }) do |f|
        = render partial: 'form', object:f, as: :form, locals: {comment: @comment}
        .control-group
          .controls
            = f.submit t('buttons.update'), disable_with: t('buttons.update'), class: 'btn btn-primary'

app/views/comments/new.html.haml
= javascript_include_tag "entry_form"
.container-fluid
  .row-fluid
    .page_header
      .pagination.pagination_base
        %ul
          %li= link_to('', root_path, class: 'icon-home')
          %li= link_to('', thread_message_path(@message), class: 'icon-comment')
  .row-fluid
    .entry_form
      = form_for([@message, @comment], multipart: true, html: { id:'entry_form', class: 'form-horizontal' }) do |f|
        = render partial: 'form', object:f, as: :form, locals: {comment: @comment}
        .control-group
          .controls
            = f.submit t('buttons.create'), disable_with: t('buttons.create'), class: 'btn btn-primary'

app/views/comments/show.html.haml
.container-fluid
  .row-fluid
    .page_header
      .pagination.pagination_base
        %ul
          %li= link_to('', root_path, class: 'icon-home')
          %li= link_to('', thread_message_path(@message, anchor: @comment.id), class: 'icon-comment')
  = render partial: 'thread', object: @comment, as: :entry,
    locals: {button_display: false, thumbnail_display: false}
  .row-fluid.photo_base
    - @comment.photos.each do |photo|
      = render(partial: 'photos/photo', object: photo)

= render(partial: 'social_javascript')