config/routes.rb
TheFoveonBbs::Application.routes.draw do
  namespace :admin do
    resources :messages, only: [:index] do
      collection do
        delete :bulk_destroy
      end
    end
    resources :comments, only: [:index] do
      collection do
        delete :bulk_destroy
      end
    end
  end

  resources :messages do
    collection do
      get 'trees'
      get 'feed'
    end
    member do
      get 'thread'
      get 'delete_confirm'
    end
    resources :comments do
      member do
        get 'delete_confirm'
        get 'reply'
      end
    end
  end
  resources :photos

  root to: 'messages#trees'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :entry, polymorphic: true

  mount_uploader :photo_data, PhotoDataUploader

  before_save :extract_exif, if: :photo_data_changed?

  validates :no, presence: true
  validates :photo_data, presence: true

  def formatted_exif
    data = Hash.new
    data[:Make] = self.exif['Make'] if self.exif['Make']
    data[:Model] = self.exif['Model'] if self.exif['Model']
    data[:DateTimeOriginal] = self.exif['DateTimeOriginal'] if self.exif['DateTimeOriginal']
    data[:ExposureBiasValue] = "#{exif['ExposureBiasValue']}" if self.exif['ExposureBiasValue']
    data[:ExposureMode] = I18n.t("exif.ExposureMode.#{self.exif['ExposureMode']}") if self.exif['ExposureMode']
    data[:ExposureProgram] = I18n.t("exif.ExposureProgram.#{self.exif['ExposureProgram']}") if self.exif['ExposureProgram']
    data[:ExposureTime] = self.exif['ExposureTime'] if self.exif['ExposureTime']
    data[:FNumber] = self.exif['FNumber'] if self.exif['FNumber']
    data[:FocalLength] = self.exif['FocalLength'] if self.exif['FocalLength']
    data[:ISOSpeedRatings] = self.exif['ISOSpeedRatings'] if self.exif['ISOSpeedRatings']
    data[:Flash] = I18n.t("exif.Flash.#{self.exif['Flash']}") if self.exif['Flash']
    data
  end

  def extract_exif
    tmp_exif = Hash.new
    begin
      image = Magick::Image.read(photo_data.current_path).first
      image.get_exif_by_entry.each do |datas|
        key = datas.shift
        tmp_exif[key] = datas.present? ? datas.first : nil
      end
      self.exif = tmp_exif
    rescue => e
      Rails.logger.error(e.message)
      raise e
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_photo, only: [:show, :edit, :update, :destroy]

  def show
  end

  private

  def find_photo
    @photo = Photo.find(params[:id])
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_photo.html.haml
.row-fluid
  .span12
    .photo_base
      .row-fluid
        .span7
          .photo_vga
            = link_to(image_tag(photo.photo_data.vga.to_s, class: 'img-polaroid'), photo.photo_data.url.to_s, target: '_blank')
            %br
            = render(partial: 'facebook_like_button', object: photo_url(photo), as: :href)
            = render(partial: 'twitter_share_button', object: photo_url(photo), as: :href, locals: {comment: "> #{photo.title}"})
        .span5
          %table.table
            %thead
              %tr
                %th(colspan=2)= photo.title
            %tbody
              - photo.formatted_exif.each do |key, value|
                %tr
                  %td= t('exif.attributes')[key]
                  %td= value

app/views/photos/_photo_smart_phone.html.haml
.row-fluid
  .span12
    .photo_base
      .photo_vga
        = link_to(image_tag(photo.photo_data.vga.to_s, class: 'img-polaroid'), photo.photo_data.url.to_s, target: '_blank')
        %br
        = render(partial: 'facebook_like_button', object: photo_url(photo), as: :href)
        = render(partial: 'twitter_share_button', object: photo_url(photo), as: :href, locals: {comment: "> #{photo.title}"})
.row-fluid
  .span12
    .exif_base
      %table.table
        %thead
          %tr
            %th(colspan=2)= photo.title
        %tbody
          - photo.formatted_exif.each do |key, value|
            %tr
              %td= t('exif.attributes')[key]
              %td= value

app/views/photos/show.html.haml
.container-fluid
  .row-fluid
    .span12
      .page_header
        .pagination.pagination_base
          %ul
            %li= link_to('', root_path, class: 'icon-home')
            -case @photo.entry
            -when Message
              %li= link_to('', thread_message_path(@photo.entry), class: 'icon-comment')
            -when Comment
              %li= link_to('', thread_message_path(@photo.entry.message, anchor: @photo.entry.id), class: 'icon-comment')
  = render(partial: 'photo',  object: @photo)

= render(partial: 'social_javascript')