config/routes.rb
TheFoveonBbs::Application.routes.draw do
  namespace :admin do
    resources :messages, only: [:index] do
      collection do
        delete :bulk_destroy
      end
    end
    resources :comments, only: [:index] do
      collection do
        delete :bulk_destroy
      end
    end
  end

  resources :messages do
    collection do
      get 'trees'
      get 'feed'
    end
    member do
      get 'thread'
      get 'delete_confirm'
    end
    resources :comments do
      member do
        get 'delete_confirm'
        get 'reply'
      end
    end
  end
  resources :photos

  root to: 'messages#trees'
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  layout 'admin/application'
  http_basic_authenticate_with name: "master", password: "asai"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Jpmobile::ViewSelector

  before_action :set_locale
  before_action :disable_mobile_view!, if: :tablet?

  helper_method :tablet?

  # Set locale in response to client's browser setting.
  def set_locale
    accept_language = request.headers['Accept-Language']
    return if accept_language.blank?

    available = %w{en ja}
    accept_language.split(',').each do |locale_set|
      locale = locale_set.split(';').first
      if available.include?(locale)
        I18n.locale = locale
        break
      end
    end
  end

  def tablet?
    request.mobile && request.mobile.tablet?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_delete_form.html.haml
= form.label :password
= form.password_field :password, class: 'input-small'
= form.submit t('buttons.delete'), disable_with: t('buttons.delete'), class: 'btn btn-danger'
- if form.object.errors[:password].present?
  .alert.alert-error
    - form.object.errors.full_messages_for(:password).each do |error|
      = error

app/views/application/_entry_form.html.haml
.control-group
  .controls
    = render partial: "entry_form_error", object: entry, as: :entry, locals: {attribute: :base}
.control-group
  = form.label :title, class: 'control-label required', id: 'title_label'
  .controls
    = form.text_field :title, class: 'input-xlarge', id: 'title'
    = render partial: "entry_form_error", object: entry, as: :entry, locals: {attribute: :title}
.control-group
  = form.label :author, class: 'control-label required', id: 'author_label'
  .controls
    = form.text_field :author, class: 'input-xlarge', id: 'author'
    = render partial: "entry_form_error", object: entry, as: :entry, locals: {attribute: :author}
.control-group
  = form.label :password, class: 'control-label required', id: 'password_label'
  .controls
    = form.password_field :password, class: 'input-xlarge', id: 'password'
    = render partial: "entry_form_error", object: entry, as: :entry, locals: {attribute: :password}
.control-group
  = form.label :content, class: 'control-label required', id: 'content_label'
  .controls
    = form.text_area :content, class: 'input-xxlarge', size: '300x15', id: 'content'
    = render partial: "entry_form_error", object: entry, as: :entry, locals: {attribute: :content}
.control-group
  = form.label :mail, class: 'control-label'
  .controls
    = form.text_field :mail, class: 'input-xlarge'
    = render partial: "entry_form_error", object: entry, as: :entry, locals: {attribute: :mail}
.control-group
  = form.label :homepage, class: 'control-label'
  .controls
    = form.text_field :homepage, class: 'input-xxlarge'
    = render partial: "entry_form_error", object: entry, as: :entry, locals: {attribute: :homepage}

= form.fields_for :photos do |photo_form|
  .control-group
    = photo_form.label :photo_data, class: 'control-label'
    = photo_form.hidden_field :no
    .controls
      = photo_form.text_field :title
      = photo_form.file_field :photo_data
      = photo_form.hidden_field :photo_data_cache
      - if photo_form.object.persisted?
        = photo_form.check_box :_destroy
        = photo_form.label :_destroy
      - if photo_form.object.errors.present?
        .alert.alert-error
          - photo_form.object.errors.full_messages.each do |msg|
            = msg
            %br

app/views/application/_entry_form_error.html.haml
- if entry.errors[attribute].present?
  .alert.alert-error
    - entry.errors.full_messages_for(attribute).each do |error|
      = error

app/views/application/_facebook_like_button.html.haml
%iframe(src="//www.facebook.com/plugins/like.php?href=#{ERB::Util.url_encode(href)}&send=false&layout=button_count&width=100&show_faces=false&font&colorscheme=light&action=like&height=20&appId=#{Settings.facebook.app_id}" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100px; height:20px;" allowTransparency="true")

app/views/application/_pager.html.haml
.row-fluid
  .span12
    .page_header
      %span.icon_base
        .pagination.pagination_base
          %ul
            %li= link_to('', root_path, class: 'icon-home')
            %li= link_to('', new_message_path, class: 'icon-file')
      %span.pager_base
        - if tablet?
          = paginate messages, window: 2
        - else
          = paginate messages
      %span.search_base
        = form_tag(trees_messages_path, method: :get, class: 'form-search') do
          .input-append
            = text_field_tag :words, params['words'], class: 'input-small search-query'
            = submit_tag(t('buttons.search'), name: nil, class: 'btn')

app/views/application/_pager_smart_phone.html.haml
.row-fluid
  .page_header
    %span.icon_base
      .pagination.pagination_base
        %ul
          %li= link_to('', root_path, class: 'icon-home')
          %li= link_to('', new_message_path, class: 'icon-file')
    %span.pager_base
      .btn-group
        %a(class="btn dropdown-toggle" data-toggle="dropdown" href="#")
          No.
          %span.caret
        = paginate messages, window: 3
    %span.search_base
      = form_tag(trees_messages_path, method: :get, class: 'form-search') do
        = text_field_tag :words, params['words'], class: 'input-mini'
        = submit_tag(t('buttons.search'), name: nil, class: 'btn')

app/views/application/_social_javascript.html.haml
= render(partial: 'twitter_javascript')

app/views/application/_twitter_share_button.html.haml
%A(href="https://twitter.com/share" class="twitter-share-button" data-url="#{href}" data-text=comment data-lang="#{I18n.locale}")
  Twitter